**Hand written Digit Prediction**-Classification Analysis

Import Library

In [3]:
import pandas as pd

In [4]:
import numpy as np

In [5]:
import matplotlib.pyplot as plt

Import Data

In [6]:
from sklearn.datasets import load_digits

In [7]:
df = load_digits()

In [8]:
_, axes = plt.subplots(nrows = 1, ncols = 4, figsize = (10,3))
for ax, image, label in zip(axes, df.images, df.target):
  ax.set_axis_off()
  ax.imshow(image, cmap = plt.cm.gray_r, interpolation = "nearest")
  ax.set_title("training: %i" %label)

Data Preprocessing

In [7]:
df.images.shape

(1797, 8, 8)

In [9]:
df.images[0]

array([[ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.],
       [ 0.,  0., 13., 15., 10., 15.,  5.,  0.],
       [ 0.,  3., 15.,  2.,  0., 11.,  8.,  0.],
       [ 0.,  4., 12.,  0.,  0.,  8.,  8.,  0.],
       [ 0.,  5.,  8.,  0.,  0.,  9.,  8.,  0.],
       [ 0.,  4., 11.,  0.,  1., 12.,  7.,  0.],
       [ 0.,  2., 14.,  5., 10., 12.,  0.,  0.],
       [ 0.,  0.,  6., 13., 10.,  0.,  0.,  0.]])

In [10]:
df.images[0].shape

(8, 8)

In [11]:
len(df.images)

1797

In [12]:
n_samples = len(df.images)
data = df.images.reshape((n_samples, -1))

In [13]:
data[0]

array([ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0., 13., 15., 10.,
       15.,  5.,  0.,  0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  4.,
       12.,  0.,  0.,  8.,  8.,  0.,  0.,  5.,  8.,  0.,  0.,  9.,  8.,
        0.,  0.,  4., 11.,  0.,  1., 12.,  7.,  0.,  0.,  2., 14.,  5.,
       10., 12.,  0.,  0.,  0.,  0.,  6., 13., 10.,  0.,  0.,  0.])

In [14]:
data[0].shape

(64,)

In [15]:
data.shape

(1797, 64)

Scaling Image Data

In [16]:
data.min()

0.0

In [17]:
data.max()

16.0

In [18]:
data = data/16

In [19]:
data.min()

0.0

In [20]:
data.max()

1.0

In [21]:
data[0]

array([0.    , 0.    , 0.3125, 0.8125, 0.5625, 0.0625, 0.    , 0.    ,
       0.    , 0.    , 0.8125, 0.9375, 0.625 , 0.9375, 0.3125, 0.    ,
       0.    , 0.1875, 0.9375, 0.125 , 0.    , 0.6875, 0.5   , 0.    ,
       0.    , 0.25  , 0.75  , 0.    , 0.    , 0.5   , 0.5   , 0.    ,
       0.    , 0.3125, 0.5   , 0.    , 0.    , 0.5625, 0.5   , 0.    ,
       0.    , 0.25  , 0.6875, 0.    , 0.0625, 0.75  , 0.4375, 0.    ,
       0.    , 0.125 , 0.875 , 0.3125, 0.625 , 0.75  , 0.    , 0.    ,
       0.    , 0.    , 0.375 , 0.8125, 0.625 , 0.    , 0.    , 0.    ])

Train Test Split Data

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
x_train, x_test, y_train, y_test = train_test_split(data, df.target,test_size = 0.3)

In [24]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((1257, 64), (540, 64), (1257,), (540,))

Random Forest Model

In [25]:
from sklearn.ensemble import RandomForestClassifier

In [26]:
rf = RandomForestClassifier()

In [27]:
rf.fit(x_train, y_train)

RandomForestClassifier()

Predict Test Data

In [28]:
y_pred = rf.predict(x_test)

In [29]:
y_pred

array([2, 4, 4, 1, 7, 7, 4, 4, 2, 5, 0, 6, 8, 6, 4, 8, 9, 8, 9, 2, 3, 4,
       0, 2, 2, 3, 8, 7, 2, 1, 2, 8, 1, 7, 6, 2, 1, 9, 1, 3, 8, 0, 1, 2,
       6, 0, 6, 6, 8, 3, 6, 6, 4, 6, 6, 1, 8, 0, 0, 1, 8, 2, 5, 2, 9, 1,
       4, 2, 1, 6, 8, 7, 0, 1, 5, 4, 7, 1, 3, 3, 4, 1, 2, 8, 7, 4, 0, 6,
       1, 4, 8, 2, 6, 5, 9, 2, 9, 0, 7, 2, 2, 5, 5, 6, 2, 9, 9, 6, 8, 2,
       2, 7, 4, 1, 8, 9, 3, 3, 0, 3, 7, 8, 7, 5, 8, 4, 3, 5, 3, 3, 6, 2,
       9, 9, 7, 9, 5, 0, 2, 5, 0, 0, 6, 9, 8, 0, 6, 3, 8, 1, 1, 9, 1, 5,
       4, 7, 7, 5, 7, 3, 3, 8, 3, 0, 7, 9, 0, 4, 5, 5, 8, 4, 1, 8, 9, 8,
       2, 1, 6, 6, 7, 0, 9, 7, 0, 1, 7, 8, 4, 5, 6, 9, 8, 9, 3, 4, 5, 2,
       2, 7, 7, 1, 8, 7, 4, 8, 7, 4, 7, 4, 8, 0, 6, 0, 1, 2, 4, 5, 0, 5,
       6, 2, 1, 4, 7, 8, 5, 9, 1, 9, 1, 2, 0, 6, 9, 1, 1, 8, 6, 4, 8, 4,
       8, 3, 6, 7, 1, 2, 1, 7, 7, 4, 9, 9, 0, 1, 5, 4, 0, 3, 3, 6, 5, 1,
       7, 0, 2, 7, 7, 7, 6, 5, 1, 8, 4, 2, 5, 3, 1, 7, 4, 1, 3, 1, 2, 6,
       2, 9, 3, 7, 5, 6, 5, 5, 0, 1, 1, 0, 2, 7, 1,

In [30]:
from sklearn.metrics import confusion_matrix, classification_report

In [31]:
confusion_matrix(y_test,y_pred)

array([[56,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 60,  0,  0,  0,  0,  0,  0,  1,  0],
       [ 0,  0, 55,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 48,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 56,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 53,  1,  0,  0,  0],
       [ 1,  1,  0,  0,  0,  0, 50,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 54,  0,  0],
       [ 0,  3,  0,  0,  0,  0,  0,  0, 48,  0],
       [ 0,  0,  0,  1,  0,  1,  0,  1,  2, 48]])

In [32]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99        56
           1       0.94      0.98      0.96        61
           2       1.00      1.00      1.00        55
           3       0.98      1.00      0.99        48
           4       1.00      1.00      1.00        56
           5       0.98      0.98      0.98        54
           6       0.98      0.96      0.97        52
           7       0.98      1.00      0.99        54
           8       0.94      0.94      0.94        51
           9       1.00      0.91      0.95        53

    accuracy                           0.98       540
   macro avg       0.98      0.98      0.98       540
weighted avg       0.98      0.98      0.98       540

